// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/storager (interfaces: FileReaderWriter)

// Package storemocks is a generated GoMock package.
package storemocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileReaderWriter is a mock of FileReaderWriter interface.
type MockFileReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderWriterMockRecorder
}

// MockFileReaderWriterMockRecorder is the mock recorder for MockFileReaderWriter.
type MockFileReaderWriterMockRecorder struct {
	mock *MockFileReaderWriter
}

// NewMockFileReaderWriter creates a new mock instance.
func NewMockFileReaderWriter(ctrl *gomock.Controller) *MockFileReaderWriter {
	mock := &MockFileReaderWriter{ctrl: ctrl}
	mock.recorder = &MockFileReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileReaderWriter) EXPECT() *MockFileReaderWriterMockRecorder {
	return m.recorder
}

// CheckFile mocks base method.
func (m *MockFileReaderWriter) CheckFile(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckFile indicates an expected call of CheckFile.
func (mr *MockFileReaderWriterMockRecorder) CheckFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFile", reflect.TypeOf((*MockFileReaderWriter)(nil).CheckFile), arg0)
}

// Read mocks base method.
func (m *MockFileReaderWriter) Read(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFileReaderWriterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFileReaderWriter)(nil).Read), arg0)
}

// Write mocks base method.
func (m *MockFileReaderWriter) Write(arg0 []byte, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockFileReaderWriterMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFileReaderWriter)(nil).Write), arg0, arg1)
}
