// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/storager (interfaces: StoreConfig)

// Package storemocks is a generated GoMock package.
package storemocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStoreConfig is a mock of StoreConfig interface.
type MockStoreConfig struct {
	ctrl     *gomock.Controller
	recorder *MockStoreConfigMockRecorder
}

// MockStoreConfigMockRecorder is the mock recorder for MockStoreConfig.
type MockStoreConfigMockRecorder struct {
	mock *MockStoreConfig
}

// NewMockStoreConfig creates a new mock instance.
func NewMockStoreConfig(ctrl *gomock.Controller) *MockStoreConfig {
	mock := &MockStoreConfig{ctrl: ctrl}
	mock.recorder = &MockStoreConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreConfig) EXPECT() *MockStoreConfigMockRecorder {
	return m.recorder
}

// GetDatabaseDSN mocks base method.
func (m *MockStoreConfig) GetDatabaseDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabaseDSN indicates an expected call of GetDatabaseDSN.
func (mr *MockStoreConfigMockRecorder) GetDatabaseDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseDSN", reflect.TypeOf((*MockStoreConfig)(nil).GetDatabaseDSN))
}

// GetFileStoragePath mocks base method.
func (m *MockStoreConfig) GetFileStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFileStoragePath indicates an expected call of GetFileStoragePath.
func (mr *MockStoreConfigMockRecorder) GetFileStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileStoragePath", reflect.TypeOf((*MockStoreConfig)(nil).GetFileStoragePath))
}
