// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/config (interfaces: GetFileReader)

// Package mocks is a generated GoMock package.
package mocks

import (
	bufio "bufio"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockGetFileReader is a mock of GetFileReader interface
type MockGetFileReader struct {
	ctrl     *gomock.Controller
	recorder *MockGetFileReaderMockRecorder
}

// MockGetFileReaderMockRecorder is the mock recorder for MockGetFileReader
type MockGetFileReaderMockRecorder struct {
	mock *MockGetFileReader
}

// NewMockGetFileReader creates a new mock instance
func NewMockGetFileReader(ctrl *gomock.Controller) *MockGetFileReader {
	mock := &MockGetFileReader{ctrl: ctrl}
	mock.recorder = &MockGetFileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGetFileReader) EXPECT() *MockGetFileReaderMockRecorder {
	return m.recorder
}

// GetReader mocks base method
func (m *MockGetFileReader) GetReader(arg0 string) (*bufio.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReader", arg0)
	ret0, _ := ret[0].(*bufio.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReader indicates an expected call of GetReader
func (mr *MockGetFileReaderMockRecorder) GetReader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReader", reflect.TypeOf((*MockGetFileReader)(nil).GetReader), arg0)
}
