// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/server (interfaces: SrvService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storager "github.com/GlebZigert/url_shortener.git/internal/storager"
	gomock "github.com/golang/mock/gomock"
)

// MockSrvService is a mock of SrvService interface.
type MockSrvService struct {
	ctrl     *gomock.Controller
	recorder *MockSrvServiceMockRecorder
}

// MockSrvServiceMockRecorder is the mock recorder for MockSrvService.
type MockSrvServiceMockRecorder struct {
	mock *MockSrvService
}

// NewMockSrvService creates a new mock instance.
func NewMockSrvService(ctrl *gomock.Controller) *MockSrvService {
	mock := &MockSrvService{ctrl: ctrl}
	mock.recorder = &MockSrvServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSrvService) EXPECT() *MockSrvServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSrvService) Delete(arg0 []string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSrvServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSrvService)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockSrvService) GetAll() *[]*storager.Shorten {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]*storager.Shorten)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSrvServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSrvService)(nil).GetAll))
}

// GetUrlsCount mocks base method.
func (m *MockSrvService) GetUrlsCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrlsCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetUrlsCount indicates an expected call of GetUrlsCount.
func (mr *MockSrvServiceMockRecorder) GetUrlsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrlsCount", reflect.TypeOf((*MockSrvService)(nil).GetUrlsCount))
}

// GetUsersCount mocks base method.
func (m *MockSrvService) GetUsersCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetUsersCount indicates an expected call of GetUsersCount.
func (mr *MockSrvServiceMockRecorder) GetUsersCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCount", reflect.TypeOf((*MockSrvService)(nil).GetUsersCount))
}

// Origin mocks base method.
func (m *MockSrvService) Origin(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Origin", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Origin indicates an expected call of Origin.
func (mr *MockSrvServiceMockRecorder) Origin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Origin", reflect.TypeOf((*MockSrvService)(nil).Origin), arg0)
}

// Short mocks base method.
func (m *MockSrvService) Short(arg0 string, arg1 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Short", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Short indicates an expected call of Short.
func (mr *MockSrvServiceMockRecorder) Short(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Short", reflect.TypeOf((*MockSrvService)(nil).Short), arg0, arg1)
}
