// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/server (interfaces: SrvConfig)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSrvConfig is a mock of SrvConfig interface.
type MockSrvConfig struct {
	ctrl     *gomock.Controller
	recorder *MockSrvConfigMockRecorder
}

// MockSrvConfigMockRecorder is the mock recorder for MockSrvConfig.
type MockSrvConfigMockRecorder struct {
	mock *MockSrvConfig
}

// NewMockSrvConfig creates a new mock instance.
func NewMockSrvConfig(ctrl *gomock.Controller) *MockSrvConfig {
	mock := &MockSrvConfig{ctrl: ctrl}
	mock.recorder = &MockSrvConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSrvConfig) EXPECT() *MockSrvConfigMockRecorder {
	return m.recorder
}

// GetBaseURL mocks base method.
func (m *MockSrvConfig) GetBaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseURL indicates an expected call of GetBaseURL.
func (mr *MockSrvConfigMockRecorder) GetBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseURL", reflect.TypeOf((*MockSrvConfig)(nil).GetBaseURL))
}

// GetDatabaseDSN mocks base method.
func (m *MockSrvConfig) GetDatabaseDSN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseDSN")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabaseDSN indicates an expected call of GetDatabaseDSN.
func (mr *MockSrvConfigMockRecorder) GetDatabaseDSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseDSN", reflect.TypeOf((*MockSrvConfig)(nil).GetDatabaseDSN))
}

// GetENABLEHTTPSflag mocks base method.
func (m *MockSrvConfig) GetENABLEHTTPSflag() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetENABLEHTTPSflag")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetENABLEHTTPSflag indicates an expected call of GetENABLEHTTPSflag.
func (mr *MockSrvConfigMockRecorder) GetENABLEHTTPSflag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetENABLEHTTPSflag", reflect.TypeOf((*MockSrvConfig)(nil).GetENABLEHTTPSflag))
}

// GetFileStoragePath mocks base method.
func (m *MockSrvConfig) GetFileStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFileStoragePath indicates an expected call of GetFileStoragePath.
func (mr *MockSrvConfigMockRecorder) GetFileStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileStoragePath", reflect.TypeOf((*MockSrvConfig)(nil).GetFileStoragePath))
}

// GetFlagLogLevel mocks base method.
func (m *MockSrvConfig) GetFlagLogLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlagLogLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFlagLogLevel indicates an expected call of GetFlagLogLevel.
func (mr *MockSrvConfigMockRecorder) GetFlagLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlagLogLevel", reflect.TypeOf((*MockSrvConfig)(nil).GetFlagLogLevel))
}

// GetNumWorkers mocks base method.
func (m *MockSrvConfig) GetNumWorkers() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumWorkers")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNumWorkers indicates an expected call of GetNumWorkers.
func (mr *MockSrvConfigMockRecorder) GetNumWorkers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumWorkers", reflect.TypeOf((*MockSrvConfig)(nil).GetNumWorkers))
}

// GetRunAddr mocks base method.
func (m *MockSrvConfig) GetRunAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRunAddr indicates an expected call of GetRunAddr.
func (mr *MockSrvConfigMockRecorder) GetRunAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunAddr", reflect.TypeOf((*MockSrvConfig)(nil).GetRunAddr))
}

// GetSECRETKEY mocks base method.
func (m *MockSrvConfig) GetSECRETKEY() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSECRETKEY")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSECRETKEY indicates an expected call of GetSECRETKEY.
func (mr *MockSrvConfigMockRecorder) GetSECRETKEY() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSECRETKEY", reflect.TypeOf((*MockSrvConfig)(nil).GetSECRETKEY))
}

// GetTOKENEXP mocks base method.
func (m *MockSrvConfig) GetTOKENEXP() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTOKENEXP")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTOKENEXP indicates an expected call of GetTOKENEXP.
func (mr *MockSrvConfigMockRecorder) GetTOKENEXP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTOKENEXP", reflect.TypeOf((*MockSrvConfig)(nil).GetTOKENEXP))
}
