// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/middleware (interfaces: SrcCIDR)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSrcCIDR is a mock of SrcCIDR interface.
type MockSrcCIDR struct {
	ctrl     *gomock.Controller
	recorder *MockSrcCIDRMockRecorder
}

// MockSrcCIDRMockRecorder is the mock recorder for MockSrcCIDR.
type MockSrcCIDRMockRecorder struct {
	mock *MockSrcCIDR
}

// NewMockSrcCIDR creates a new mock instance.
func NewMockSrcCIDR(ctrl *gomock.Controller) *MockSrcCIDR {
	mock := &MockSrcCIDR{ctrl: ctrl}
	mock.recorder = &MockSrcCIDRMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSrcCIDR) EXPECT() *MockSrcCIDRMockRecorder {
	return m.recorder
}

// GetCIDR mocks base method.
func (m *MockSrcCIDR) GetCIDR() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIDR")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCIDR indicates an expected call of GetCIDR.
func (mr *MockSrcCIDRMockRecorder) GetCIDR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIDR", reflect.TypeOf((*MockSrcCIDR)(nil).GetCIDR))
}
