// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/middleware/middlewares.go

// Package mock_middleware is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockmdlAuth is a mock of mdlAuth interface.
type MockmdlAuth struct {
	ctrl     *gomock.Controller
	recorder *MockmdlAuthMockRecorder
}

// MockmdlAuthMockRecorder is the mock recorder for MockmdlAuth.
type MockmdlAuthMockRecorder struct {
	mock *MockmdlAuth
}

// NewMockmdlAuth creates a new mock instance.
func NewMockmdlAuth(ctrl *gomock.Controller) *MockmdlAuth {
	mock := &MockmdlAuth{ctrl: ctrl}
	mock.recorder = &MockmdlAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmdlAuth) EXPECT() *MockmdlAuthMockRecorder {
	return m.recorder
}

// BuildJWTString mocks base method.
func (m *MockmdlAuth) BuildJWTString(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJWTString", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJWTString indicates an expected call of BuildJWTString.
func (mr *MockmdlAuthMockRecorder) BuildJWTString(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJWTString", reflect.TypeOf((*MockmdlAuth)(nil).BuildJWTString), id)
}

// CheckNewFlag mocks base method.
func (m *MockmdlAuth) CheckNewFlag(ctx context.Context) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNewFlag", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckNewFlag indicates an expected call of CheckNewFlag.
func (mr *MockmdlAuthMockRecorder) CheckNewFlag(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNewFlag", reflect.TypeOf((*MockmdlAuth)(nil).CheckNewFlag), ctx)
}

// CheckUID mocks base method.
func (m *MockmdlAuth) CheckUID(ctx context.Context) (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUID", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckUID indicates an expected call of CheckUID.
func (mr *MockmdlAuthMockRecorder) CheckUID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUID", reflect.TypeOf((*MockmdlAuth)(nil).CheckUID), ctx)
}

// GetUserID mocks base method.
func (m *MockmdlAuth) GetUserID(tokenString string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", tokenString)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockmdlAuthMockRecorder) GetUserID(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockmdlAuth)(nil).GetUserID), tokenString)
}

// SetNewFlag mocks base method.
func (m *MockmdlAuth) SetNewFlag(ctx context.Context, fl bool) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewFlag", ctx, fl)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// SetNewFlag indicates an expected call of SetNewFlag.
func (mr *MockmdlAuthMockRecorder) SetNewFlag(ctx, fl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewFlag", reflect.TypeOf((*MockmdlAuth)(nil).SetNewFlag), ctx, fl)
}

// SetUID mocks base method.
func (m *MockmdlAuth) SetUID(ctx context.Context, user int) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUID", ctx, user)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// SetUID indicates an expected call of SetUID.
func (mr *MockmdlAuthMockRecorder) SetUID(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUID", reflect.TypeOf((*MockmdlAuth)(nil).SetUID), ctx, user)
}

// MockmdlLogger is a mock of mdlLogger interface.
type MockmdlLogger struct {
	ctrl     *gomock.Controller
	recorder *MockmdlLoggerMockRecorder
}

// MockmdlLoggerMockRecorder is the mock recorder for MockmdlLogger.
type MockmdlLoggerMockRecorder struct {
	mock *MockmdlLogger
}

// NewMockmdlLogger creates a new mock instance.
func NewMockmdlLogger(ctrl *gomock.Controller) *MockmdlLogger {
	mock := &MockmdlLogger{ctrl: ctrl}
	mock.recorder = &MockmdlLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmdlLogger) EXPECT() *MockmdlLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockmdlLogger) Error(msg string, fields map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg, fields)
}

// Error indicates an expected call of Error.
func (mr *MockmdlLoggerMockRecorder) Error(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockmdlLogger)(nil).Error), msg, fields)
}

// Info mocks base method.
func (m *MockmdlLogger) Info(msg string, fields map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg, fields)
}

// Info indicates an expected call of Info.
func (mr *MockmdlLoggerMockRecorder) Info(msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockmdlLogger)(nil).Info), msg, fields)
}
