// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/server (interfaces: SrvPinger)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSrvPinger is a mock of SrvPinger interface.
type MockSrvPinger struct {
	ctrl     *gomock.Controller
	recorder *MockSrvPingerMockRecorder
}

// MockSrvPingerMockRecorder is the mock recorder for MockSrvPinger.
type MockSrvPingerMockRecorder struct {
	mock *MockSrvPinger
}

// NewMockSrvPinger creates a new mock instance.
func NewMockSrvPinger(ctrl *gomock.Controller) *MockSrvPinger {
	mock := &MockSrvPinger{ctrl: ctrl}
	mock.recorder = &MockSrvPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSrvPinger) EXPECT() *MockSrvPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSrvPinger) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSrvPingerMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSrvPinger)(nil).Ping), arg0)
}
