// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/middleware (interfaces: MdlAuth)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMdlAuth is a mock of MdlAuth interface.
type MockMdlAuth struct {
	ctrl     *gomock.Controller
	recorder *MockMdlAuthMockRecorder
}

// MockMdlAuthMockRecorder is the mock recorder for MockMdlAuth.
type MockMdlAuthMockRecorder struct {
	mock *MockMdlAuth
}

// NewMockMdlAuth creates a new mock instance.
func NewMockMdlAuth(ctrl *gomock.Controller) *MockMdlAuth {
	mock := &MockMdlAuth{ctrl: ctrl}
	mock.recorder = &MockMdlAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMdlAuth) EXPECT() *MockMdlAuthMockRecorder {
	return m.recorder
}

// BuildJWTString mocks base method.
func (m *MockMdlAuth) BuildJWTString(arg0 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJWTString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJWTString indicates an expected call of BuildJWTString.
func (mr *MockMdlAuthMockRecorder) BuildJWTString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJWTString", reflect.TypeOf((*MockMdlAuth)(nil).BuildJWTString), arg0)
}

// CheckNewFlag mocks base method.
func (m *MockMdlAuth) CheckNewFlag(arg0 context.Context) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNewFlag", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckNewFlag indicates an expected call of CheckNewFlag.
func (mr *MockMdlAuthMockRecorder) CheckNewFlag(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNewFlag", reflect.TypeOf((*MockMdlAuth)(nil).CheckNewFlag), arg0)
}

// CheckUID mocks base method.
func (m *MockMdlAuth) CheckUID(arg0 context.Context) (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUID", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckUID indicates an expected call of CheckUID.
func (mr *MockMdlAuthMockRecorder) CheckUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUID", reflect.TypeOf((*MockMdlAuth)(nil).CheckUID), arg0)
}

// GetUserID mocks base method.
func (m *MockMdlAuth) GetUserID(arg0 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockMdlAuthMockRecorder) GetUserID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockMdlAuth)(nil).GetUserID), arg0)
}

// SetNewFlag mocks base method.
func (m *MockMdlAuth) SetNewFlag(arg0 context.Context, arg1 bool) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewFlag", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// SetNewFlag indicates an expected call of SetNewFlag.
func (mr *MockMdlAuthMockRecorder) SetNewFlag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewFlag", reflect.TypeOf((*MockMdlAuth)(nil).SetNewFlag), arg0, arg1)
}

// SetUID mocks base method.
func (m *MockMdlAuth) SetUID(arg0 context.Context, arg1 int) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUID", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// SetUID indicates an expected call of SetUID.
func (mr *MockMdlAuthMockRecorder) SetUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUID", reflect.TypeOf((*MockMdlAuth)(nil).SetUID), arg0, arg1)
}
