// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GlebZigert/url_shortener.git/internal/middleware (interfaces: MdlUserStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMdlUserStore is a mock of MdlUserStore interface.
type MockMdlUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockMdlUserStoreMockRecorder
}

// MockMdlUserStoreMockRecorder is the mock recorder for MockMdlUserStore.
type MockMdlUserStoreMockRecorder struct {
	mock *MockMdlUserStore
}

// NewMockMdlUserStore creates a new mock instance.
func NewMockMdlUserStore(ctrl *gomock.Controller) *MockMdlUserStore {
	mock := &MockMdlUserStore{ctrl: ctrl}
	mock.recorder = &MockMdlUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMdlUserStore) EXPECT() *MockMdlUserStoreMockRecorder {
	return m.recorder
}

// CreateNextUID mocks base method.
func (m *MockMdlUserStore) CreateNextUID() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNextUID")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNextUID indicates an expected call of CreateNextUID.
func (mr *MockMdlUserStoreMockRecorder) CreateNextUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNextUID", reflect.TypeOf((*MockMdlUserStore)(nil).CreateNextUID))
}
